feat: add wayslog's profile
RustTalk/guests pull request #3
Opened 2022-02-07 12:38 UTC by wayslog

2022-02-07 13:01 UTC, doyoubi commented on podcasts/2022-02-07-wayslog.org
> +   rust写的不多不少的时候总会去思考，这个地方是不是达到了 zero coast，能不能通过design和lifetime的组合来规避掉这种开销。
zero cost嘿嘿

2022-02-07 13:25 UTC, jiacai2050 requested changes

2022-02-07 13:25 UTC, jiacai2050 commented on podcasts/2022-02-07-wayslog.org
> +   我们很轻松的写出了原先C版本(twemproxy）1/4的性能，但是再往上提升就很难提升了，我们做了很多的优化，效果都不甚立项。
不甚理想

2022-02-14 04:42 UTC, jiacai2050 approved these changes

2022-02-14 04:43 UTC, merged